### ISSUE TITLE
webui password-less

### ISSUE THREAD

**Issue by azim0ff** [nickiv/node-red-huawei-sms#6]
Hi, thank you for the awesome node-red module. Running it on an RPi + e3372 combination.

Just wanted to send a quick note. When webui is not password protected, an error is generated during access even if the password field is left blank. With password enabled everything works as expected. Is it feasible to allow unpassworded access by leaving the password field blank?

**Comment by nickiv** [comment]
Hi! Your welcome!)

I did not test it with empty password. It did not even occure to me that password could be disabled.

Frankly I do not want to support such a risky setup in this module. I suggest you to be security aware and set a password.

Surely you can make fork if you want.

**Comment by azim0ff** [comment]
Hey, thanks for replying. No worries if you don't feel like adding it, just thought I'd ask.

BTW, it's not that unusual to see unpassworded setups, with e3372 anyways. Situation obviously changes for e8372 and the like. So really, it depends on your setup.
